image:
  pullPolicy: Always
  repository: mediawiki
  tag: latest
namespace: mediawiki
wikidb:
  dbip: 1.2.3.4
wikidbvalues:
  keyspacename: wikidatabase
  rolename: wiki
  username: wiki
replicaCount: 1
resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  min:
    limits:
      cpu: 645m
      memory: 1420Mi
    requests:
      cpu: 4m
      memory: 1420Mi
  requests:
    cpu: 2000m
    memory: 4Gi
service:
  name: mediawiki
  port: 80
  type: ClusterIP
serviceAccount:
  name: mediawiki
