apiVersion: v1
kind: Service
metadata:
  name: {{ template "mediawiki.name" .}}-service
  labels:
    app: {{ template "mediawiki.name" .}}
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http  
  selector:
    app: {{ template "mediawiki.name" .}}
